### ISSUE TITLE
[Bug]: Hadoop user invalid when changed twice

### ISSUE THREAD

**Issue by XBaith** [NetEase/amoro#1157]
### What happened?

Set a normal iceberg catalog user name in Authentication(simple mode), AMS throw the below exception:
```
2023-02-24 08:55:40,501 ERROR [Optimize Plan Thread Queue-30001] [com.netease.arctic.ams.server.service.impl.OptimizeQueueService] [] - iceberg.db.table plan failed, continue
org.apache.iceberg.exceptions.RuntimeIOException: Failed to open input stream for file: hdfs://nameservice1/iceberg/raw/table/metadata/snap-3691431149648318397-1-c8d3f023-094b-45e9-a7e0-bdd613bdcf43.avro
        at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:179) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:320) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:237) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.ManifestLists.read(ManifestLists.java:46) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:141) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.dataManifests(BaseSnapshot.java:163) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.DataTableScan.planFiles(DataTableScan.java:85) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseTableScan.planFiles(BaseTableScan.java:197) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.DataTableScan.planFiles(DataTableScan.java:30) ~[iceberg-core-0.13.2.jar:?]
        at com.netease.arctic.ams.server.service.impl.OptimizeQueueService$OptimizeQueueWrapper.plan(OptimizeQueueService.java:683) ~[arctic-ams-server-0.4.0.jar:?]
        at com.netease.arctic.ams.server.service.impl.OptimizeQueueService$OptimizeQueueWrapper.lambda$poll$0(OptimizeQueueService.java:504) ~[arctic-ams-server-0.4.0.jar:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied: user=arctic, access=EXECUTE, inode="/iceberg":user:group:drwxrwx---
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:400)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkTraverse(FSPermissionChecker.java:316)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:243)
        at org.apache.sentry.hdfs.SentryINodeAttributesProvider$SentryPermissionEnforcer.checkPermission(SentryINodeAttributesProvider.java:86)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:194)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkTraverse(FSPermissionChecker.java:605)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkTraverse(FSDirectory.java:1804)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkTraverse(FSDirectory.java:1822)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.resolvePath(FSDirectory.java:674)
        at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:150)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1909)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:735)
```

When I change it back to root user, AMS can read table information which normal users can't access, but it doesn't work for OptimizePlaner.

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. start with super user
2. change to normal user that can acessable a part of tables
3. change it back to super user

### Relevant log output

```shell
2023-02-24 09:39:07,346 ERROR [Metastore Scheduled Commit Worker 0] [com.netease.arctic.ams.server.optimize.OptimizeCommitWorker] [] - Optimize Committer Worker-0 com.netease.arctic.ams.server.optimize.TableOptimizeItem@7f918069 unexpected commit error 
java.lang.Exception: unexpected commit error 
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.commit(IcebergOptimizeCommit.java:117) ~[arctic-ams-server-0.4.0.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.commitOptimizeTasks(TableOptimizeItem.java:939) ~[arctic-ams-server-0.4.0.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCommitWorker.run(OptimizeCommitWorker.java:49) ~[arctic-ams-server-0.4.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_332]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_332]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_332]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_332]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_332]
Caused by: org.apache.iceberg.exceptions.RuntimeIOException: Failed to open input stream for file: hdfs://nameservice1/iceberg/raw/table/metadata/snap-3999212525989012873-1-3d8c9999-70ef-48bf-b84d-80de94bce200.avro
        at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:179) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:320) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:237) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.ManifestLists.read(ManifestLists.java:46) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:141) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.deleteManifests(BaseSnapshot.java:171) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validationHistory(MergingSnapshotProducer.java:489) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:357) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:316) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseRewriteFiles.validate(BaseRewriteFiles.java:108) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:162) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:283) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:282) ~[iceberg-core-0.13.2.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.minorCommit(IcebergOptimizeCommit.java:165) ~[arctic-ams-server-0.4.0.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.commit(IcebergOptimizeCommit.java:96) ~[arctic-ams-server-0.4.0.jar:?]
        ... 9 more
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied: user=arctic, access=EXECUTE, inode="/iceberg":user:group:drwxrwx---
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:400)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkTraverse(FSPermissionChecker.java:316)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:243)
        at org.apache.sentry.hdfs.SentryINodeAttributesProvider$SentryPermissionEnforcer.checkPermission(SentryINodeAttributesProvider.java:86)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:194)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkTraverse(FSPermissionChecker.java:605)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkTraverse(FSDirectory.java:1804)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkTraverse(FSDirectory.java:1822)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.resolvePath(FSDirectory.java:674)
        at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:150)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1909)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:735)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:415)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)

        at sun.reflect.GeneratedConstructorAccessor98.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_332]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_332]
        at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:849) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:836) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:825) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:330) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:289) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:274) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1064) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:332) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:914) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:320) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:237) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.ManifestLists.read(ManifestLists.java:46) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:141) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.deleteManifests(BaseSnapshot.java:171) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validationHistory(MergingSnapshotProducer.java:489) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:357) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:316) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseRewriteFiles.validate(BaseRewriteFiles.java:108) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:162) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:283) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:282) ~[iceberg-core-0.13.2.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.minorCommit(IcebergOptimizeCommit.java:165) ~[arctic-ams-server-0.4.0.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.commit(IcebergOptimizeCommit.java:96) ~[arctic-ams-server-0.4.0.jar:?]
        ... 9 more
Caused by: org.apache.hadoop.ipc.RemoteException: Permission denied: user=arctic, access=EXECUTE, inode="/iceberg":user:group:drwxrwx---
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:400)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkTraverse(FSPermissionChecker.java:316)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:243)
        at org.apache.sentry.hdfs.SentryINodeAttributesProvider$SentryPermissionEnforcer.checkPermission(SentryINodeAttributesProvider.java:86)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:194)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkTraverse(FSPermissionChecker.java:605)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkTraverse(FSDirectory.java:1804)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkTraverse(FSDirectory.java:1822)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.resolvePath(FSDirectory.java:674)
        at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:150)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1909)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:735)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:415)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)

        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1507) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1453) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy62.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:259) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy63.getBlockLocations(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:847) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:836) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:825) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:330) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:289) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:274) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1064) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:332) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:329) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:914) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:320) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:237) ~[iceberg-bundled-guava-0.13.2.jar:?]
        at org.apache.iceberg.ManifestLists.read(ManifestLists.java:46) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:141) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseSnapshot.deleteManifests(BaseSnapshot.java:171) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validationHistory(MergingSnapshotProducer.java:489) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:357) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:316) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseRewriteFiles.validate(BaseRewriteFiles.java:108) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:162) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:283) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:282) ~[iceberg-core-0.13.2.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.minorCommit(IcebergOptimizeCommit.java:165) ~[arctic-ams-server-0.4.0.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.commit(IcebergOptimizeCommit.java:96) ~[arctic-ams-server-0.4.0.jar:?]
        ... 9 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@XBaith 
When you change the catalog authorization user from an invalid to a valid one, the optimizing planner still uses the old one while the table controller uses the new one. Do I understand you correctly?

BTW, I'm curious if the optimizer can use the correct authorization user after the change.

**Comment by XBaith** [comment]
> 

correct.

Optimizer worked fine after the change
