### ISSUE TITLE
[Bug]: FlinkOptimizer run fail on hadoop3

### ISSUE THREAD

**Issue by Pandas886** [NetEase/amoro#1509]
### What happened?

hadoop version： 3.3.4
flink version： 1.15
---
when ams submit FlinkOptimizer job  on yarn，it fail.
i found the subimt cmd from ams log as below:
```
export HADOOP_CONF_DIR=/opt/edp/flink1/conf/ && export JVM_ARGS=-Djava.security.krb5.conf=/opt/krb5.conf && export FLINK_CONF_DIR=/opt/edp/flink1/conf/ \
 && /home/flink/apache-flink//bin/flink run -m yarn-cluster  -ytm 1024 -yjm 1024 -c com.netease.arctic.optimizer.flink.FlinkOptimizer \
  /home/flink/arctic-0.4.1/plugin/optimize/OptimizeJob.jar  -a zookeeper://test-1:2181,test-2:2181,test-3:2181/arctic -q 2 -p 1 --heart-beat 60000 -id 3 -es false -mm 512
```

i test the flink example on yarn is no problem，like below：
```

/home/flink/apache-flink/bin/flink run -m yarn-cluster  -ytm 1024 -yjm 1024 -c org.apache.flink.streaming.examples.wordcount.WordCount /home/flink/apache-flink/examples/streaming/WordCount.jar \
 --input hdfs:///tmp/ --output hdfs:///tmp/out
```

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

Optimizer

### Relevant log output

```shell
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/flink/apache-flink/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/flink/apache-hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-06-03 09:12:14,149 WARN  org.apache.flink.yarn.configuration.YarnLogConfigUtil        [] - The configuration directory ('/opt/edp/flink1/conf/') already contains a LOG4J config file.If you want to use logback, then please d
elete or rename the log configuration file.
2023-06-03 09:12:15,061 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - No path for the flink jar passed. Using the location of class org.apache.flink.yarn.YarnClusterDescriptor to locate the jar
2023-06-03 09:12:15,127 WARN  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Job Clusters are deprecated since Flink 1.15. Please use an Application Cluster/Application Mode instead.
2023-06-03 09:12:15,412 INFO  org.apache.hadoop.yarn.client.ConfiguredRMFailoverProxyProvider [] - Failing over to rm2
2023-06-03 09:12:15,628 INFO  org.apache.hadoop.conf.Configuration                         [] - resource-types.xml not found
2023-06-03 09:12:15,629 INFO  org.apache.hadoop.yarn.util.resource.ResourceUtils           [] - Unable to find 'resource-types.xml'.
2023-06-03 09:12:15,840 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Cluster specification: ClusterSpecification{masterMemoryMB=1024, taskManagerMemoryMB=1024, slotsPerTaskManager=1}
java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:68)
        at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:65)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:52)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.loadClass(FlinkUserCodeClassLoaders.java:172)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.hadoop.fs.FileSystem.loadFileSystems(FileSystem.java:3379)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3424)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
        at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:288)
        at org.apache.flink.yarn.YarnClusterDescriptor.startAppMaster(YarnClusterDescriptor.java:790)
        at org.apache.flink.yarn.YarnClusterDescriptor.deployInternal(YarnClusterDescriptor.java:616)
        at org.apache.flink.yarn.YarnClusterDescriptor.deployJobCluster(YarnClusterDescriptor.java:484)
        at org.apache.flink.client.deployment.executors.AbstractJobClusterExecutor.execute(AbstractJobClusterExecutor.java:82)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:2095)
        at org.apache.flink.client.program.StreamContextEnvironment.executeAsync(StreamContextEnvironment.java:188)
        at org.apache.flink.client.program.StreamContextEnvironment.execute(StreamContextEnvironment.java:119)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1969)
        at com.netease.arctic.optimizer.flink.FlinkOptimizer.tryExecute(FlinkOptimizer.java:265)
        at com.netease.arctic.optimizer.flink.FlinkOptimizer.main(FlinkOptimizer.java:260)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:841)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:240)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1085)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1163)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1163)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
The default hadoop version of arctic project is 2.9.2,  you can change the version in pom.xml and re-complie the flink-optimizer module.

**Comment by wangtaohz** [comment]
> The default hadoop version of arctic project is 2.9.2, you can change the version in pom.xml and re-complie the flink-optimizer module.

AFAIK, some other users in the community have tested arctic on Hadoop 3.1.x and 3.2.x, and it worked well. Although I still have no idea about whether arctic can run with Hadoop 3.3.x, it looks more like a jar conflict issue according to the exception stack. 

```
2023-06-03 09:12:15,840 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Cluster specification: ClusterSpecification{masterMemoryMB=1024, taskManagerMemoryMB=1024, slotsPerTaskManager=1}
java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
        at java.lang.ClassLoader.defineClass1(Native Method)
```

You can try to troubleshoot it by analyzing the dependencies.

BTW, your Flink version is 1.15, and the Optimizer needs to be repackaged because the default package is based on Flink 1.12. Here is how to do it https://github.com/NetEase/arctic/discussions/645

**Comment by zhoujinsong** [comment]
@fantasyni Have you fixed the bug after changing the dependency versions?

In addition, I think it is necessary to optimize the user experience for users with different infrastructures, instead of always struggling to find the root cause of the problem and manually modifying configurations and repackaging.

How do you think? @wangtaohz  @baiyangtx

**Comment by baiyangtx** [comment]
> @fantasyni Have you fixed the bug after changing the dependency versions?
> 
> In addition, I think it is necessary to optimize the user experience for users with different infrastructures, instead of always struggling to find the root cause of the problem and manually modifying configurations and repackaging.
> 
> How do you think? @wangtaohz @baiyangtx

Yes, I think it's better to have a profile to indicate the Hadoop version like ` mvn -Phadoop3` .

And I think we could release multi-packages with different Hadoop versions

**Comment by Pandas886** [comment]
I think it's better to prebuild the OptimizeJob jar with different flink version and hadoop version

**Comment by baiyangtx** [comment]
> I think it's better to prebuild the OptimizeJob jar with different flink version and hadoop version

Would you be willing to submit a PR to fix this issue?

**Comment by czy006** [comment]
> I think it's better to prebuild the OptimizeJob jar with different flink version and hadoop version

Currently, the Hadoop version and the Flink version can be selected for compilation during the compilation phase, so this problem has been solved. If you still have any questions, please reopen the ticket.
