### ISSUE TITLE
[Bug]For flinkcontainer optimizer, When making a connection via ams in high availability mode, NoSuchMethodError is encountered

### ISSUE THREAD

**Issue by xieyi888** [NetEase/amoro#1611]
### What happened?

When use flink job as optimizer ,and  making a connection via ams in high availability mode, NoClassDefFoundError is encountered

### Affects Versions

master/0.4.x

### What engines are you seeing the problem on?

Optimizer

### How to reproduce

ams  high availability mode
use flink job as optimizer 
flink 1.12
flink parameter
`-hb 60000 -p 1 -a zookeeper://{zookeeper-endpoint-list} -g{OPTIMIZER_GROUP_NAME} -m{OPTIMIZER_MEMORY}`

### Relevant log output

```shell
2023-06-26 15:08:59,941 INFO  com.netease.arctic.optimizer.OptimizerToucher                [] - Starting optimizer toucher with configuration:OptimizerConfig{amsUrl=zookeeper://10.105.5.84:2181/arctic-xieyi-test, executionParallel=1, memorySize=2048, groupName=analysis_xieyi_external, heartBeat=60000, extendDiskStorage=false, rocksDBBasePath=null, memoryStorageSize=512, resourceId=null}
2023-06-26 15:08:59,947 INFO  org.apache.flink.runtime.io.network.partition.consumer.SingleInputGate [] - Converting recovered input channels (1 channels)
2023-06-26 15:09:00,063 ERROR com.netease.arctic.optimizer.AbstractOptimizerOperator       [] - Call ams got an error and will try again later
java.lang.NoSuchMethodError: org.apache.zookeeper.server.quorum.flexible.QuorumMaj.<init>(Ljava/util/Map;)V
	at org.apache.curator.framework.imps.EnsembleTracker.<init>(EnsembleTracker.java:57) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.<init>(CuratorFrameworkImpl.java:187) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.curator.framework.CuratorFrameworkFactory$Builder.build(CuratorFrameworkFactory.java:188) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ZookeeperService.newClient(ZookeeperService.java:65) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ZookeeperService.<init>(ZookeeperService.java:41) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ZookeeperService.getInstance(ZookeeperService.java:48) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ArcticThriftUrl.parserZookeeperUrl(ArcticThriftUrl.java:135) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ArcticThriftUrl.parse(ArcticThriftUrl.java:77) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ThriftClientPool$1.create(ThriftClientPool.java:96) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ThriftClientPool$1.create(ThriftClientPool.java:90) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:69) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:565) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:307) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:428) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:232) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.ThriftClientPool.iface(ThriftClientPool.java:218) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.ams.api.client.OptimizingClientPools.getClient(OptimizingClientPools.java:41) ~[arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.optimizer.AbstractOptimizerOperator.callAms(AbstractOptimizerOperator.java:33) [arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.optimizer.OptimizerToucher.checkToken(OptimizerToucher.java:55) [arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.optimizer.OptimizerToucher.start(OptimizerToucher.java:41) [arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkToucher.run(FlinkToucher.java:45) [arctic-ams-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist_2.12-ne-flink-1.12.4-1.1.7.1.jar:ne-flink-1.12.4-1.1.7.1]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66) [flink-dist_2.12-ne-flink-1.12.4-1.1.7.1.jar:ne-flink-1.12.4-1.1.7.1]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:263) [flink-dist_2.12-ne-flink-1.12.4-1.1.7.1.jar:ne-flink-1.12.4-1.1.7.1]
```
```


### Anything else

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by HuangFru** [comment]
I've encountered a similar problem:
```
2023-07-26 14:18:02,879 ERROR [JettyServerThreadPool-71] [io.javalin.Javalin] [] - Exception occurred while servicing http-request
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/netease/arctic/shaded/org/apache/curator/shaded/com/google/common/base/Preconditions
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_152]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:991) ~[?:1.8.0_152]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_152]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_152]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_152]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:1.8.0_152]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_152]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_152]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_152]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_152]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:1.8.0_152]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_152]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_152]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89) ~[javalin-4.6.1.jar:4.6.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[jakarta.servlet-api-4.0.3.jar:4.0.3]
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58) ~[javalin-4.6.1.jar:4.6.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[jakarta.servlet-api-4.0.3.jar:4.0.3]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52) ~[javalin-4.6.1.jar:4.6.1]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_152]
Caused by: java.lang.NoClassDefFoundError: com/netease/arctic/shaded/org/apache/curator/shaded/com/google/common/base/Preconditions
        at com.netease.arctic.ams.api.resource.Resource$Builder.build(Resource.java:111) ~[arctic-ams-api-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.dashboard.controller.OptimizerController.scaleOutOptimizer(OptimizerController.java:207) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_152]
        ... 54 more
Caused by: java.lang.ClassNotFoundException: com.netease.arctic.shaded.org.apache.curator.shaded.com.google.common.base.Preconditions
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_152]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
        at com.netease.arctic.ams.api.resource.Resource$Builder.build(Resource.java:111) ~[arctic-ams-api-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.dashboard.controller.OptimizerController.scaleOutOptimizer(OptimizerController.java:207) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_152]
        ... 54 more
```
