### ISSUE TITLE
[Bug]: Failed to create Tag to Iceberg Format Table In Terminal

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#2311]
### What happened?

I can create a branch to Iceberg Format Table in the Terminal, but I get an error when trying to create a tag.

<img width="1378" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/37e46054-55e0-4dc1-9dba-265b0d1aa414">

### Affects Versions

master/0.7.0

### What engines are you seeing the problem on?

Spark

### How to reproduce

1.Create an Iceberg Format Table
2.Create tag to this Table, like

ALTER TABLE iceberg.db.user CREATE TAG tagtest2112 AS OF VERSION 8334851092700841180;

### Relevant log output

```shell
2023/11/15 15:52:01 new sql script submit, current thread pool state. [Active: 1, PoolSize: 1]
2023/11/15 15:52:01 fetch terminal session: node0r6yb18yr1y9w16v8yhebhfub80.node0-SIMPLE-wangtao-iceberg
2023/11/15 15:52:01 session configuration: catalog-url-base => thrift://127.0.0.1:1260
2023/11/15 15:52:01 session configuration: catalog.iceberg.uri => http://127.0.0.1:1630/api/iceberg/rest
2023/11/15 15:52:01 session configuration: catalog.iceberg.warehouse => iceberg
2023/11/15 15:52:01 session configuration: spark.sql.arctic.refresh-catalog-before-usage => true
2023/11/15 15:52:01 session configuration: catalog.iceberg.catalog-impl => org.apache.iceberg.rest.RESTCatalog
2023/11/15 15:52:01 session configuration: spark.sql.catalog.iceberg.warehouse => iceberg
2023/11/15 15:52:01 session configuration: catalog.iceberg.table.self-optimizing.group => local
2023/11/15 15:52:01 session configuration: spark.sql.catalog.iceberg.catalog-impl => org.apache.iceberg.rest.RESTCatalog
2023/11/15 15:52:01 session configuration: session.catalogs => iceberg
2023/11/15 15:52:01 session configuration: spark.sql.catalog.iceberg => org.apache.iceberg.spark.SparkCatalog
2023/11/15 15:52:01 session configuration: session.fetch-size => 1000
2023/11/15 15:52:01 session configuration: spark.sql.catalog.iceberg.table-formats => ICEBERG
2023/11/15 15:52:01 session configuration: catalog.iceberg.table-formats => ICEBERG
2023/11/15 15:52:01 session configuration: spark.sql.catalog.iceberg.uri => http://127.0.0.1:1630/api/iceberg/rest
2023/11/15 15:52:01 session configuration: spark.sql.catalog.iceberg.table.self-optimizing.group => local
2023/11/15 15:52:01 session configuration: session.catalog.iceberg.connector => iceberg
2023/11/15 15:52:01  
2023/11/15 15:52:01 prepare execute statement, line:153
2023/11/15 15:52:01 ALTER TABLE iceberg.db.user CREATE TAG tagtest2112 AS OF VERSION 8334851092700841180
2023/11/15 15:52:01 meet exception during execution.
2023/11/15 15:52:01 org.apache.spark.sql.catalyst.parser.ParseException: 
no viable alternative at input 'ALTER TABLE iceberg.db.user CREATE'(line 1, pos 28)

== SQL ==
ALTER TABLE iceberg.db.user CREATE TAG tagtest2112 AS OF VERSION 8334851092700841180
----------------------------^^^

	at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:255)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:124)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:49)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:75)
	at com.netease.arctic.spark.sql.catalyst.parser.ArcticSqlExtensionsParser.parsePlan(ArcticSqlExtensionsParser.scala:176)
	at org.apache.spark.sql.catalyst.parser.extensions.IcebergSparkSqlExtensionsParser.parsePlan(IcebergSparkSqlExtensionsParser.scala:103)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:616)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:616)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
	at com.netease.arctic.server.terminal.local.LocalTerminalSession.executeStatement(LocalTerminalSession.java:78)
	at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.executeStatement(TerminalSessionContext.java:281)
	at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.execute(TerminalSessionContext.java:245)
	at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.lambda$get$0(TerminalSessionContext.java:206)
	at com.netease.arctic.table.TableMetaStore.call(TableMetaStore.java:234)
	at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:209)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1918)
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:209)
	at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.get(TerminalSessionContext.java:196)
	at com.netease.arctic.server.terminal.TerminalSessionContext$ExecutionTask.get(TerminalSessionContext.java:171)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HuangFru** [comment]
![image](https://github.com/NetEase/amoro/assets/68625618/a17a26b9-386a-4168-b668-59f9f95c7001)

It looks like the IcebergSparkSessionExtensions here are hacked by ArcticSparkExtensions.

**Comment by HuangFru** [comment]
According to https://github.com/apache/iceberg/pull/8217 and https://github.com/apache/iceberg/pull/8661, Spark 3.1 does not support `CREATE TAG` DDL on iceberg 1.3. And 3.1 is deprecated on the higher versions🥲. So you must build the project by hadoop3 to use Spark3.3 which supports this.

**Comment by wangtaohz** [comment]
> According to https://github.com/apache/iceberg/pull/8217 and https://github.com/apache/iceberg/pull/8661, Spark 3.1 does not support CREATE TAG DDL on iceberg 1.3. And 3.1 is deprecated on the higher versions🥲. So you must build the project by hadoop3 to use Spark3.3 which supports this.

Thank you for providing the information. I have tested it locally with Spark 3.3, and it was solved.
