### ISSUE TITLE
[Bug]: When the token expires, successful \`OptimizingTask\` should not be retried

### ISSUE THREAD

**Issue by rfyu** [NetEase/amoro#2631]
### What happened?

When the optimizer expires, if we reset successful tasks, it will cause the following exception, which will prevent other tasks that should have been put into the retry queue from being added

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Relevant log output

```shell
2024-03-12 06:27:31,862 ERROR [optimizer-keeper-thread] [com.netease.arctic.server.DefaultOptimizingService] [] - OptimizerKeeper has encountered a problem.
com.netease.arctic.server.exception.IllegalTaskStateException: Illegal Task of OptimizingTaskId(processId:1710195822728, taskId:7) status from SUCCESS to PLANNED
        at com.netease.arctic.server.optimizing.TaskRuntime$TaskStatusMachine.accept(TaskRuntime.java:345) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.optimizing.TaskRuntime.lambda$reset$1(TaskRuntime.java:112) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_291]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_291]
        at com.netease.arctic.server.persistence.PersistentBase.doAsTransaction(PersistentBase.java:61) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.persistence.StatedPersistentBase.invokeConsisitency(StatedPersistentBase.java:52) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.optimizing.TaskRuntime.reset(TaskRuntime.java:110) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.optimizing.OptimizingQueue.retryTask(OptimizingQueue.java:292) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.DefaultOptimizingService$OptimizerKeeper.retryTask(DefaultOptimizingService.java:563) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at com.netease.arctic.server.DefaultOptimizingService$OptimizerKeeper.lambda$null$0(DefaultOptimizingService.java:549) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_291]
        at com.netease.arctic.server.DefaultOptimizingService$OptimizerKeeper.lambda$run$1(DefaultOptimizingService.java:549) ~[amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_291]
        at com.netease.arctic.server.DefaultOptimizingService$OptimizerKeeper.run(DefaultOptimizingService.java:545) [amoro-ams-server-0.7.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majin1102** [comment]
Sucess status should never be reset.

I think this is the right logic
