### ISSUE TITLE
[Bug]: Metadata file for version 2 is missing

### ISSUE THREAD

**Issue by pan3793** [NetEase/amoro#624]
### What happened?

Unexpected result when syncing data using Kyuubi Arctic Playground.

### Affects Versions

0.3.2

### What engines are you seeing the problem on?

Flink

### How to reproduce

```
git clone https://github.com/NetEase/kyuubi-arctic-playground.git
cd kyuubi-arctic-playground
./build-image.sh
docker compose up

docker exec -it mysql-arctic-cdc \
  java -cp lakehouse-benchmark-ingestion-1.0-SNAPSHOT.jar \
  com.netease.arctic.benchmark.ingestion.MainRunner \
  -confDir /opt/lakehouse_benchmark_ingestion/conf \
  -sinkType arctic -sinkDatabase arctic_db
```

### Relevant log output

```shell
2022-11-16 14:56:10,744 ERROR [Metastore Scheduled Check Worker 5] [com.netease.arctic.ams.server.optimize.OptimizeCheckTask] [] - unexpected check
 error local_catalog.arctic_db.customer
org.apache.iceberg.exceptions.ValidationException: Metadata file for version 2 is missing
        at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:106) ~[iceberg-core-0.12.0.jar:?]
        at com.netease.arctic.op.ArcticHadoopTableOperations.lambda$refresh$0(ArcticHadoopTableOperations.java:38) ~[arctic-core-0.3.2.jar:?]
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:315) ~[arctic-core-0.3.2.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_352]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_352]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873) ~[hadoop-common-2.9.2.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:313) ~[arctic-core-0.3.2.jar:?]
        at com.netease.arctic.io.ArcticHadoopFileIO.doAs(ArcticHadoopFileIO.java:177) ~[arctic-core-0.3.2.jar:?]
        at com.netease.arctic.op.ArcticHadoopTableOperations.refresh(ArcticHadoopTableOperations.java:38) ~[arctic-core-0.3.2.jar:?]
        at org.apache.iceberg.BaseTable.refresh(BaseTable.java:59) ~[iceberg-core-0.12.0.jar:?]
        at com.netease.arctic.table.BaseUnkeyedTable.refresh(BaseUnkeyedTable.java:100) ~[arctic-core-0.3.2.jar:?]
        at com.netease.arctic.ams.server.utils.UnKeyedTableUtil.getSnapshotId(UnKeyedTableUtil.java:27) ~[arctic-ams-server-0.3.2.jar:?]
        at com.netease.arctic.ams.server.optimize.BaseOptimizePlan.tableNeedPlan(BaseOptimizePlan.java:301) ~[arctic-ams-server-0.3.2.jar:?]
        at com.netease.arctic.ams.server.optimize.BaseOptimizePlan.plan(BaseOptimizePlan.java:141) ~[arctic-ams-server-0.3.2.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.updateTableOptimizeStatus(TableOptimizeItem.java:386) ~[arctic-ams-server-0.3.2
.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCheckTask.check(OptimizeCheckTask.java:57) ~[arctic-ams-server-0.3.2.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCheckTask.run(OptimizeCheckTask.java:47) ~[arctic-ams-server-0.3.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_352]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_352]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_352]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]

ams-error.log
```

### Anything else

I checked the storage, there is no `v2.metadata.json` on the base path.

And the content of `version-hint.text` is `1`.

<img width="1585" alt="image" src="https://user-images.githubusercontent.com/26535726/202218326-e04148d7-f837-4f46-818d-7c62687e637e.png">
<img width="523" alt="image" src="https://user-images.githubusercontent.com/26535726/202218399-0bb159b6-da19-46dc-88b3-03adb7ed35c1.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
